package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/asheshgoplani/agent-deck/internal/session"
	"github.com/asheshgoplani/agent-deck/internal/watcher"
)

// channelConfig is the input format from the bash issue-watcher's channels.json.
type channelConfig struct {
	Name        string `json:"name"`
	ProjectPath string `json:"project_path"`
	Group       string `json:"group"`
	Prefix      string `json:"prefix"`
}

// handleWatcher dispatches watcher subcommands.
func handleWatcher(profile string, args []string) {
	if len(args) == 0 {
		printWatcherHelp()
		return
	}

	switch args[0] {
	case "import":
		handleWatcherImport(profile, args[1:])
	case "help", "--help", "-h":
		printWatcherHelp()
	default:
		fmt.Fprintf(os.Stderr, "Unknown watcher command: %s\n", args[0])
		fmt.Fprintln(os.Stderr)
		printWatcherHelp()
		os.Exit(1)
	}
}

// handleWatcherImport reads a bash issue-watcher channels.json and generates
// Go watcher configuration files (watcher.toml per channel + clients.json entries).
func handleWatcherImport(profile string, args []string) {
	if len(args) != 1 {
		fmt.Fprintln(os.Stderr, "Usage: agent-deck watcher import <path-to-channels.json>")
		os.Exit(1)
	}

	inputPath := filepath.Clean(args[0])

	// Resolve output directory via session.WatcherDir()
	outputDir, err := session.WatcherDir()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error resolving watcher directory: %v\n", err)
		os.Exit(1)
	}

	if err := importChannels(inputPath, outputDir); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

// parseChannelsJSON reads and parses a channels.json file.
// Returns the parsed channel map or an error if the file cannot be read or parsed.
func parseChannelsJSON(path string) (map[string]channelConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read channels.json: %w", err)
	}
	var channels map[string]channelConfig
	if err := json.Unmarshal(data, &channels); err != nil {
		return nil, fmt.Errorf("parse channels.json: %w", err)
	}
	if channels == nil {
		channels = make(map[string]channelConfig)
	}
	return channels, nil
}

// generateWatcherToml creates the watcher.toml content for a channel.
func generateWatcherToml(channelID string, cfg channelConfig) string {
	return fmt.Sprintf(`# Auto-generated by: agent-deck watcher import
# Source channel: %s (%s)

[watcher]
name = %q
type = "slack"

[source]
# TODO: set your ntfy topic (all Slack channels share one ntfy topic from the Cloudflare Worker)
topic = ""
server = "https://ntfy.sh"

[routing]
conductor = %q
group = %q
`, channelID, cfg.Name, cfg.Prefix, cfg.Prefix, cfg.Group)
}

// mergeClientsJSON loads existing clients.json (if any), merges new entries, and writes back.
// Existing entries with the same key are overwritten by new entries (idempotent).
// Uses atomic write (temp file + rename) per threat model T-15-09.
func mergeClientsJSON(clientsPath string, newEntries map[string]watcher.ClientEntry) error {
	merged := make(map[string]watcher.ClientEntry)

	// Load existing if present
	if data, err := os.ReadFile(clientsPath); err == nil {
		if err := json.Unmarshal(data, &merged); err != nil {
			return fmt.Errorf("parse existing clients.json: %w", err)
		}
	}

	// Merge new entries (overwrite on key collision)
	for k, v := range newEntries {
		merged[k] = v
	}

	// Marshal with indentation
	data, err := json.MarshalIndent(merged, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal clients.json: %w", err)
	}

	// Atomic write: write to temp file in same directory, then rename
	dir := filepath.Dir(clientsPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create clients.json directory: %w", err)
	}

	tmp, err := os.CreateTemp(dir, ".clients-*.json.tmp")
	if err != nil {
		return fmt.Errorf("create temp file for clients.json: %w", err)
	}
	tmpName := tmp.Name()

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return fmt.Errorf("write temp clients.json: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("close temp clients.json: %w", err)
	}
	if err := os.Rename(tmpName, clientsPath); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("rename temp clients.json: %w", err)
	}

	return nil
}

// importChannels is the core logic for the import command.
// It reads a channels.json file, generates watcher.toml per channel,
// and creates/merges clients.json entries with slack:{CHANNEL_ID} keys.
func importChannels(inputPath, outputDir string) error {
	// Security: validate input path (T-15-07)
	cleanPath := filepath.Clean(inputPath)

	info, err := os.Lstat(cleanPath)
	if err != nil {
		return fmt.Errorf("cannot access %q: %w", cleanPath, err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("symlink not allowed: %q", cleanPath)
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("not a regular file: %q", cleanPath)
	}

	// Parse channels
	channels, err := parseChannelsJSON(cleanPath)
	if err != nil {
		return err
	}

	// Ensure output directory exists
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	// Sort channel IDs for deterministic output
	ids := make([]string, 0, len(channels))
	for id := range channels {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	// Build client entries and generate watcher.toml files
	clientEntries := make(map[string]watcher.ClientEntry, len(channels))

	for _, channelID := range ids {
		cfg := channels[channelID]

		// Create watcher directory
		watcherDir := filepath.Join(outputDir, cfg.Prefix)
		if err := os.MkdirAll(watcherDir, 0o755); err != nil {
			return fmt.Errorf("create watcher dir for %q: %w", cfg.Prefix, err)
		}

		// Write watcher.toml
		tomlContent := generateWatcherToml(channelID, cfg)
		tomlPath := filepath.Join(watcherDir, "watcher.toml")
		if err := os.WriteFile(tomlPath, []byte(tomlContent), 0o644); err != nil {
			return fmt.Errorf("write watcher.toml for %q: %w", cfg.Prefix, err)
		}

		// Build client entry with slack:{CHANNEL_ID} key (D-11, D-12)
		clientKey := fmt.Sprintf("slack:%s", channelID)
		clientEntries[clientKey] = watcher.ClientEntry{
			Conductor: cfg.Prefix,
			Group:     cfg.Group,
			Name:      cfg.Name,
		}
	}

	// Merge clients.json
	clientsPath := filepath.Join(outputDir, "clients.json")
	if err := mergeClientsJSON(clientsPath, clientEntries); err != nil {
		return err
	}

	// Print summary
	fmt.Printf("Imported %d channel(s)\n", len(channels))
	for _, id := range ids {
		cfg := channels[id]
		fmt.Printf("  %s -> %s/watcher.toml\n", id, cfg.Prefix)
	}
	if len(channels) > 0 {
		fmt.Println()
		fmt.Println("Note: Set the ntfy topic in each watcher.toml (all Slack channels")
		fmt.Println("share one ntfy topic from the Cloudflare Worker).")
	}
	fmt.Printf("Clients written to: %s\n", clientsPath)

	return nil
}

// printWatcherHelp prints usage for the watcher subcommand.
func printWatcherHelp() {
	fmt.Println("Usage: agent-deck watcher <command> [args]")
	fmt.Println()
	fmt.Println("Commands:")
	fmt.Println("  import <path>    Migrate bash issue-watcher channels.json to Go watcher config")
	fmt.Println()
	fmt.Println("  (More commands coming in a future release: create, start, stop, list, status, test, routes)")
}
